# Dockerfile

FROM golang:1.5.1
MAINTAINER pottava

RUN go get -u github.com/justinas/alice
RUN go get -u github.com/kurrik/oauth1a

LABEL jp.co.supinf.works.application="golang-microservices-authentication" \
      jp.co.supinf.works.license="MIT"
